CC = gcc
CFLAGS = -Wall

# Diretórios para os arquivos .c
SRCS = main.c pizza.c ingrediente.c
# Diretórios para os arquivos .o
OBJS = main.o pizza.o ingrediente.o
# Nome do executável
EXEC = pizzaria.exe

# Regra para compilar os arquivos .o
$(OBJS): %.o: %.c
	$(CC) $(CFLAGS) -c $<

# Regra para gerar o executável
$(EXEC): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(EXEC)

# Regra para executar o programa
run: $(EXEC)
	./$(EXEC)

# Regra para limpar os arquivos gerados
clean:
	rm -f $(OBJS) $(EXEC)

# Regra para compilar tudo
all: $(EXEC)
